# test text
language: node_js
env:
- SCRIPT=lint
- SCRIPT=test
script: npm run $SCRIPT
deploy:
  provider: heroku
  api_key:
    secure: SsG9Pw6wgdKf1l2SuElLq5cVqAsTwsLjDNqV2xuOC2MMj49UV7BE83bpi+X30sYCqjxWz6cdUs5cVlezjv9VBMxq/jkw12GMBr5wBjxssx/LcuuqBPu9MmVnzZ/9QQWWm2zOAHvGGL6RmWD7VPm+UY/tQj1myc2TbGSEclPoZX7grdHpiEgzkQL5Q9EK/M6ZnbEFIlniNCt5FZLRG3pF6v6YUHSgZlH5cV7Hy3jfYkQevxGExYjqG1YGnLnC676Qbb8eVaNdTOb/OQivrDzwxF5oy9tzf9TWb2a+wG3cG5G4HN4Aix4teMpuC5rZYkWZ0O83FXe+EAAtscs7bLqfTtJ8kLJc2eBtcpYgS8jtZGn0w7J0HF29j5lUiGMMZchn4mWE0OJFxVk7Rm2eOoiIZbUkGuwP1qppY2LgWtCkTU4FwBzfLvpw0exbbQYYOpX7JD3c/LZk6NbTSSiUEIDRN3xj5RoPj+petWrR/+fWL52E70mr7ceeZbojAik+wTeLtzllZba5XppLqxU4AJJ8OE1428Oc+7Z9Ww9FL86DR1INcshdNFLZOTHSpRDHr8pXlxs/zyCZhZYGucYEur6yk8MpTmKvWjVNyxYg/f24CdnEnYn9a5CtvcZ8P1PUYoRcIXZUqoTMpBygiLq5raG7TkMZPx+K1ArxSmvmxQMDwTw=
  app: fswd-lab-2-winter-2019